pipeline {
    options { timestamps() }
    agent none
    stages {
        stage('Check scm') {
            agent any
            steps {
                checkout scm
            }
        } 
        stage('Build') {
            steps {
                echo "Building ...${BUILD_NUMBER}"
                echo "Build completed"
            }
        } 
        stage('Test') {
            agent { 
                docker { 
                    image 'python:3.12-alpine' 
                    args '-u="root"'
                } 
            }
            steps {
                sh 'apk add --no-cache py3-pip'
                sh 'pip install unittest-xml-reporting'

                sh 'python lab4/test_pawnshop.py' 
            }
            post {
                always {
                    // Архівуємо звіти про тести
                    junit 'lab4/results.xml'
                }
                success {
                    echo "Application testing successfully completed"
                }
                failure {
                    echo "Oooppss!!! Tests failed!"
                }
            }
        }
    } 
}
