pipeline {
    options { timestamps() }

    environment {
        DOCKER_CRED = credentials('docker_cred')
    }

    agent none  // Вказуємо, що агент за замовчуванням не використовується

    stages {
        stage('Check scm') {
            agent any  // Вказуємо, що для цього етапу використовуємо будь-який доступний агент
            steps {
                checkout scm
            }
        } 
        stage('Build') {
            agent any  // Будь-який агент для цього етапу
            steps {
                echo "Building ...${BUILD_NUMBER}"
                echo "Build completed"
            }
        } 
        stage('Test') {
            agent { 
                docker { 
                    image 'python:3.12-alpine' 
                    args '-u root'
                } 
            }
            steps {
                sh 'apk add --no-cache py3-pip'
                sh 'pip install unittest-xml-reporting'
                sh 'python lab4/test_pawnshop.py'
            }
            post {
                always {
                    junit 'lab4/results.xml'
                }
                success {
                    echo "Application testing successfully completed"
                }
                failure {
                    echo "Oooppss!!! Tests failed!"
                }
            }
        }
        stage("Docker build") {
            agent any
            steps {
                sh 'docker build --progress=plain --no-cache -t qwertyasd0933/pawnshop_app:latest lab4/'
            }
        }
        stage("Docker login & push") {
            agent any 
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker_cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    }

                    sh 'docker tag qwertyasd0933/pawnshop_app:latest qwertyasd0933/pawnshop_app:${BUILD_NUMBER}'
                    sh 'docker push qwertyasd0933/pawnshop_app:latest'
                    sh "docker push qwertyasd0933/pawnshop_app:${BUILD_NUMBER}"
                }
            }   
        }
    }
}
